const $=id=>document.getElementById(id);
let state,queue=[],index=0,mode='current',generation=0,busy=false,history=[],rect=null,drag=null;
let saveJob=null;
async function api(url,body,signal){const response=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal}:{signal});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
function pause(ms,signal){return new Promise((resolve,reject)=>{const abort=()=>{clearTimeout(timer);reject(new DOMException('Cancelled','AbortError'));};const timer=setTimeout(()=>{signal?.removeEventListener('abort',abort);resolve();},ms);if(signal?.aborted)abort();else signal?.addEventListener('abort',abort,{once:true});});}
let upcoming=[];
const cineBuffer=new CineBuffer(async(c,viewMode,signal)=>{
 let result;do{result=await api(`/api/media/${c.file_id}/${viewMode}`,null,signal);if(result.status==='error')throw Error(result.error);if(result.status!=='ready')await pause(400,signal);}while(result.status!=='ready');
 const response=await fetch(result.url,{signal});if(!response.ok)throw Error('Cine download failed');
 // Avoid holding a large cine in JavaScript memory; let the video stream it instead.
 if(Number(response.headers.get('Content-Length'))>16*1024*1024){await response.body?.cancel();return {url:result.url};}
 return {url:result.url,blob:await response.blob()};
},{onChange:()=>{$('bufferStatus').textContent=upcoming.length?`${cineBuffer.ready(upcoming)} / ${upcoming.length} upcoming cines buffered`:'';}});
function prepareBuffer(){upcoming=queue.slice(index+1,index+4);cineBuffer.retain([current(),...upcoming].filter(Boolean),current(),mode);}
function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',3200);}
function current(){return queue[index];}
function updateCounts(){const reviewed=state.good+state.bad+state.repaired;$('progressText').textContent=`${reviewed} / ${state.total} reviewed`;$('counts').textContent=`${state.good+state.repaired} good · ${state.bad} bad`;$('progressBar').style.width=`${100*reviewed/state.total}%`;}
function rebuild(id){const filter=$('filter').value;queue=state.clips.filter(c=>filter==='all'||filter==='pending'&&!c.decision||filter==='bad'&&c.decision?.quality==='bad'||filter==='good'&&['good','repaired'].includes(c.decision?.quality));index=Math.max(0,queue.findIndex(c=>c.file_id===id));}
async function refresh(id){state=await api('/api/state');updateCounts();rebuild(id);show();}
async function show(){generation++;const token=generation,c=current();clearSwipe(true);mode='current';$('card').hidden=!c;$('empty').hidden=!!c;prepareBuffer();if(!c){$('video').pause();$('video').removeAttribute('src');$('video').load();return;}
 localStorage.setItem('cropReviewLast',c.file_id);$('patient').textContent=c.patient;$('date').textContent=c.visit_date;$('view').textContent=c.view;$('clipIndex').textContent=`Clip ${c.review_index} / ${state.total}`;$('scanner').textContent=`${c.model} · ${c.frames} frames`;$('flag').textContent=`Mask removed up to ${Math.round(c.removed_foreground_max*100)}%`;$('decision').textContent=c.decision?.quality||'Not reviewed';mode='current';setModeButtons();await media(c,token);
}
function setModeButtons(){$('current').classList.toggle('active',mode==='current');$('tissue').classList.toggle('active',mode==='tissue');$('description').textContent=mode==='current'?'Check the apex, both walls and base throughout the cine.':'Comparison only — decisions apply to the current crop. If tissue is missing from it, mark bad and use Adjust / restore.';}
async function media(c,token){$('video').pause();$('video').removeAttribute('src');$('video').load();$('mediaLoading').hidden=false;$('mediaLoading').textContent='Loading cine…';try{const url=await cineBuffer.get(c,mode);if(token!==generation)return;$('video').src=url;$('video').load();$('video').play().catch(()=>{});cineBuffer.warm(upcoming);}catch(e){if(token===generation&&e.name!=='AbortError'){$('mediaLoading').textContent=e.message;toast(e.message);}}}
$('video').addEventListener('loadeddata',()=>$('mediaLoading').hidden=true);
async function changeMode(next){if(busy||!current())return;mode=next;prepareBuffer();setModeButtons();const token=++generation;await media(current(),token);}
$('current').onclick=()=>changeMode('current');$('tissue').onclick=()=>changeMode('tissue');
async function decide(quality){if(busy||!current())return;busy=true;toast(quality==='good'?'Saving good crop…':'Saving bad crop…');const c=current();const next=queue[index+1]?.file_id;try{const [result]=await Promise.all([api('/api/decision',{file_id:c.file_id,quality:quality==='good'&&c.decision?.revision?'repaired':quality,revision:c.decision?.revision||null}),flyOut(quality)]);history.push({file_id:c.file_id,before:result.before});$('undo').disabled=false;
 // The server response confirms persistence. Update the existing queue without a second round trip.
 for(const [decision,delta] of [[c.decision,-1],[result.decision,1]])if(decision)state[decision.quality]+=delta;
 c.decision=result.decision;updateCounts();rebuild(next);await show();toast(quality==='good'?'Good crop saved':'Bad crop saved — available in the repair queue');
 }catch(e){clearSwipe();toast('Not saved: '+e.message);}finally{busy=false;}}
$('good').onclick=()=>decide('good');$('bad').onclick=()=>decide('bad');
$('undo').onclick=async()=>{if(busy||!history.length)return;const last=history.pop();try{await api('/api/decision',{file_id:last.file_id,quality:last.before?.quality||null,revision:last.before?.revision||null});$('undo').disabled=!history.length;await refresh(last.file_id);toast('Decision undone');}catch(e){history.push(last);toast(e.message);}};
$('previous').onclick=()=>{if(!busy&&index>0){index--;show();}};$('skip').onclick=()=>{if(busy)return;if(index<queue.length-1){index++;show();}else toast('End of this queue');};
$('filter').onchange=()=>{if(busy)return;rebuild();show();};$('menu').onclick=()=>$('options').hidden=!$('options').hidden;
let swipe=null;
function paintSwipe(dx){const surface=$('swipeSurface');surface.style.transform=`translate3d(${dx}px,0,0) rotate(${Math.max(-16,Math.min(16,dx*.035))}deg)`;surface.classList.toggle('toward-good',dx>0);surface.classList.toggle('toward-bad',dx<0);$('swipeGood').style.opacity=dx>0?Math.min(1,dx/65):0;$('swipeBad').style.opacity=dx<0?Math.min(1,-dx/65):0;}
function clearSwipe(instant=false){const surface=$('swipeSurface');surface.classList.remove('dragging','leaving','toward-good','toward-bad');surface.classList.toggle('resetting',instant);surface.style.transform='';surface.style.opacity='';$('swipeGood').style.opacity=0;$('swipeBad').style.opacity=0;if(swipe&&surface.hasPointerCapture(swipe.pointerId))surface.releasePointerCapture(swipe.pointerId);swipe=null;if(instant)requestAnimationFrame(()=>surface.classList.remove('resetting'));}
function flyOut(quality){const surface=$('swipeSurface');surface.classList.remove('dragging','resetting');surface.classList.add('leaving');const direction=quality==='good'?1:-1;paintSwipe(direction*Math.max(window.innerWidth,surface.clientWidth)*1.2);surface.style.opacity='0';return new Promise(resolve=>setTimeout(resolve,window.matchMedia('(prefers-reduced-motion: reduce)').matches?30:340));}
$('swipeSurface').addEventListener('pointerdown',e=>{if(busy||!current()||$('mediaLoading').hidden===false||e.isPrimary===false||e.button!==0||e.clientY>e.currentTarget.getBoundingClientRect().bottom-48)return;swipe={x:e.clientX,y:e.clientY,pointerId:e.pointerId};e.currentTarget.classList.add('dragging');e.currentTarget.setPointerCapture(e.pointerId);});
$('swipeSurface').addEventListener('pointermove',e=>{if(!swipe||e.pointerId!==swipe.pointerId)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;if(Math.abs(dy)>Math.abs(dx)+20){clearSwipe();return;}paintSwipe(dx);});
$('swipeSurface').addEventListener('pointerup',e=>{if(!swipe||e.pointerId!==swipe.pointerId)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;const threshold=Math.max(70,Math.min(120,e.currentTarget.clientWidth*.22));const accepted=Math.abs(dx)>threshold&&Math.abs(dx)>Math.abs(dy)*1.4;e.currentTarget.releasePointerCapture(e.pointerId);swipe=null;if(accepted)decide(dx>0?'good':'bad');else clearSwipe();});$('swipeSurface').addEventListener('pointercancel',()=>clearSwipe());
document.addEventListener('keydown',e=>{if($('editor').open||$('alternatives').open||/INPUT|SELECT|TEXTAREA|VIDEO/.test(e.target.tagName))return;if(e.key==='ArrowRight')decide('good');if(e.key==='ArrowLeft')decide('bad');});
function drawRect(){const r=rect||[0,0,1,1];Object.assign($('rectangle').style,{left:r[0]*100+'%',top:r[1]*100+'%',right:(1-r[2])*100+'%',bottom:(1-r[3])*100+'%'});$('repairInfo').textContent=rect?'Custom rectangle selected. Move through frames to check every wall stays inside.':'Full tissue region selected. No connected-component suppression.';}
$('fix').onclick=async()=>{const c=current();if(busy||!c)return;try{await api('/api/editor/'+c.file_id);rect=null;drawRect();$('frameSlider').max=c.frames-1;$('frameSlider').value=0;$('frameNumber').textContent='1';$('editImage').src=`/api/frame/${c.file_id}/0`;$('repairStatus').textContent='';$('saveRepair').disabled=false;$('editor').showModal();$('video').pause();}catch(e){toast(e.message);}};
$('frameSlider').oninput=()=>{$('frameNumber').textContent=Number($('frameSlider').value)+1;};$('frameSlider').onchange=()=>$('editImage').src=`/api/frame/${current().file_id}/${$('frameSlider').value}`;
function point(e){const b=$('editSurface').getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))];}
$('editSurface').addEventListener('pointerdown',e=>{if(saveJob)return;drag=point(e);e.currentTarget.setPointerCapture(e.pointerId);});
$('editSurface').addEventListener('pointermove',e=>{if(!drag)return;const p=point(e);rect=[Math.min(drag[0],p[0]),Math.min(drag[1],p[1]),Math.max(drag[0],p[0]),Math.max(drag[1],p[1])];drawRect();});
$('editSurface').addEventListener('pointerup',()=>{drag=null;});$('resetRect').onclick=()=>{rect=null;drawRect();};
function closeEditor(){if(saveJob){toast('Repair is saving; keep this window open until finished');return;}$('editor').close();}
$('closeEditor').onclick=closeEditor;$('editor').addEventListener('cancel',e=>{if(saveJob)e.preventDefault();});$('editor').addEventListener('click',e=>{if(e.target===$('editor')){const b=$('editor').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)closeEditor();}});
$('saveRepair').onclick=async()=>{if(saveJob)return;const c=current();const next=queue[index+1]?.file_id;$('saveRepair').disabled=true;try{const job=await api('/api/repair',{file_id:c.file_id,rect});saveJob=job.job;localStorage.setItem('cropRepairJob',saveJob);await pollRepair(saveJob,next);}catch(e){$('repairStatus').textContent=e.message;$('saveRepair').disabled=false;saveJob=null;localStorage.removeItem('cropRepairJob');}};
async function pollRepair(job,next){let result;do{result=await api('/api/job/'+job);$('repairStatus').textContent=result.step||'Saving repair…';if(result.status==='error')throw Error(result.error);if(result.status!=='ready')await new Promise(r=>setTimeout(r,1000));}while(result.status!=='ready');saveJob=null;localStorage.removeItem('cropRepairJob');$('editor').close();toast('New crop and both embeddings saved');await refresh(next);}
async function boot(){await refresh(localStorage.getItem('cropReviewLast'));const job=localStorage.getItem('cropRepairJob');if(job){try{saveJob=job;$('editor').showModal();$('saveRepair').disabled=true;await pollRepair(job);}catch(e){saveJob=null;localStorage.removeItem('cropRepairJob');$('editor').close();toast('Repair check: '+e.message);}}}
boot().catch(e=>toast(e.message));
$('jumpForm').onsubmit=e=>{e.preventDefault();if(busy)return;const number=Number($('jumpIndex').value);const c=state.clips.find(c=>c.review_index===number);if(!c){toast('Choose an index between 1 and '+state.total);return;}$('filter').value='all';rebuild(c.file_id);show();};
let selectedAlternative=null,alternativeToken=0,alternativeSaving=false;
$('findAlternatives').onclick=async()=>{const c=current();if(busy||!c)return;selectedAlternative=null;$('approveAlternative').disabled=true;$('alternativeList').replaceChildren();$('alternativeVideo').removeAttribute('src');$('alternatives').showModal();const token=++alternativeToken;try{let result;do{result=await api('/api/alternatives/'+c.file_id);if(token!==alternativeToken)return;$('alternativeStatus').textContent=result.step||'Finding candidates…';if(result.status==='error')throw Error(result.error);if(result.status!=='ready')await new Promise(r=>setTimeout(r,1000));}while(result.status!=='ready');$('alternativeStatus').textContent=result.candidates.length?'Ranked by view confidence and technical quality; inspect each cine.':'No confident same-view B-mode alternatives found in this visit.';for(const candidate of result.candidates){const button=document.createElement('button');button.className='alternative-option';button.textContent=`${candidate.name} · ${candidate.view} ${Math.round(candidate.probability*100)}% · ${candidate.quality.duration_seconds}s${candidate.warnings?.length?' · '+candidate.warnings.join('; '):''}`;button.onclick=async()=>{selectedAlternative=candidate.candidate_id;for(const b of $('alternativeList').children)b.classList.remove('selected');button.classList.add('selected');$('approveAlternative').disabled=true;$('alternativeStatus').textContent='Preparing candidate cine…';try{let media;do{media=await api(`/api/alternative_media/${c.file_id}/${candidate.candidate_id}`);if(media.status==='error')throw Error(media.error);if(media.status!=='ready')await new Promise(r=>setTimeout(r,500));}while(media.status!=='ready');if(selectedAlternative!==candidate.candidate_id)return;$('alternativeVideo').src=media.url;$('alternativeVideo').play().catch(()=>{});$('approveAlternative').disabled=false;$('alternativeStatus').textContent='Inspect the whole cine before approving this replacement.';}catch(e){$('alternativeStatus').textContent=e.message;}};$('alternativeList').append(button);}}catch(e){$('alternativeStatus').textContent=e.message;}};
function closeAlternatives(){if(alternativeSaving){toast('Replacement is processing');return;}alternativeToken++;$('alternativeVideo').pause();$('alternatives').close();}
$('closeAlternatives').onclick=closeAlternatives;$('alternatives').addEventListener('cancel',e=>{if(alternativeSaving)e.preventDefault();else{alternativeToken++;$('alternativeVideo').pause();}});
$('approveAlternative').onclick=async()=>{if(!selectedAlternative||alternativeSaving)return;alternativeSaving=true;$('approveAlternative').disabled=true;try{const c=current();const job=await api('/api/replace',{file_id:c.file_id,candidate_id:selectedAlternative});let result;do{result=await api('/api/job/'+job.job);$('alternativeStatus').textContent=result.step||'Saving replacement…';if(result.status==='error')throw Error(result.error);if(result.status!=='ready')await new Promise(r=>setTimeout(r,1000));}while(result.status!=='ready');alternativeSaving=false;closeAlternatives();toast('Approved replacement cropped and encoded');await refresh(c.file_id);}catch(e){alternativeSaving=false;$('approveAlternative').disabled=false;$('alternativeStatus').textContent=e.message;}};
